# Generated by Django 5.1.3 on 2024-11-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_productmodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
